# Generated by Django 5.0.3 on 2024-03-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUUIDModel',
            new_name='UserUUID',
        ),
    ]
