# Generated by Django 5.0.3 on 2024-03-28 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_useruuidmodel_useruuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruuid',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
