# Generated by Django 5.0.3 on 2024-03-28 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_useruuid_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruuid',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
