# Generated by Django 5.0.3 on 2024-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_useruuid_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('identifier', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('expiration', models.IntegerField(default=1798721699.8067467)),
            ],
        ),
        migrations.DeleteModel(
            name='UserUUID',
        ),
    ]
