# Generated by Django 5.0.3 on 2024-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_data_delete_useruuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='expiration',
            field=models.IntegerField(default=1798723995.6399934),
        ),
    ]
