# Generated by Django 5.0.3 on 2024-04-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_data_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='expiration',
            field=models.BigIntegerField(default=1712411904060),
        ),
    ]
